import type { IconType } from "react-icons";
import {
	GiAxeSword,
	GiBattleAxe,
	GiBleedingEye,
	GiBoneMace,
	GiBroadsword,
	GiBrokenShield,
	GiBubblingBowl,
	GiCheckedShield,
	GiCrestedHelmet,
	GiCrossedAxes,
	GiCrossedSwords,
	GiCrown,
	GiCrystalBall,
	GiDaemonSkull,
	GiDaggers,
	GiDeathSkull,
	GiDiabloSkull,
	GiDragonHead,
	GiEnergyShield,
	GiFireball,
	GiFireShield,
	GiFlamingClaw,
	GiFlashGrenade,
	GiGhost,
	GiGiantSquid,
	GiGlaive,
	GiHealingShield,
	GiHeartShield,
	GiIceShield,
	GiLightningShield,
	GiMagicShield,
	GiMirrorMirror,
	GiMite,
	GiMoon,
	GiMushroom,
	GiNinjaStar,
	GiOakLeaf,
	GiOctopus,
	GiOvermind,
	GiShield,
	GiShieldReflect,
	GiSkullCrossedBones,
	GiSpikedShield,
	GiSun,
	GiSwordsPower,
	GiTridentShield,
	GiWaterDrop,
	GiWingedShield,
	GiWolfHead,
	GiZeusSword,
} from "react-icons/gi";

export const gameIcons = {
	GiAxeSword,
	GiBattleAxe,
	GiBleedingEye,
	GiBoneMace,
	GiBroadsword,
	GiBrokenShield,
	GiBubblingBowl,
	GiCheckedShield,
	GiCrestedHelmet,
	GiCrossedAxes,
	GiCrossedSwords,
	GiCrown,
	GiCrystalBall,
	GiDaemonSkull,
	GiDaggers,
	GiDeathSkull,
	GiDiabloSkull,
	GiDragonHead,
	GiEnergyShield,
	GiFireball,
	GiFireShield,
	GiFlamingClaw,
	GiFlashGrenade,
	GiGhost,
	GiGiantSquid,
	GiGlaive,
	GiShield,
	GiHealingShield,
	GiHeartShield,
	GiShieldReflect,
	GiIceShield,
	GiTridentShield,
	GiLightningShield,
	GiMagicShield,
	GiMirrorMirror,
	GiMite,
	GiMoon,
	GiMushroom,
	GiNinjaStar,
	GiOakLeaf,
	GiOctopus,
	GiOvermind,
	GiSkullCrossedBones,
	GiSpikedShield,
	GiSun,
	GiSwordsPower,
	GiWaterDrop,
	GiWingedShield,
	GiWolfHead,
	GiZeusSword,
} satisfies Record<string, IconType>;

export type GameIconId = keyof typeof gameIcons;

export const GAME_ICONS = Object.keys(gameIcons) as GameIconId[];

export function getIcon(id: string): IconType {
	return gameIcons[id as GameIconId] ?? GiBroadsword;
}
